baseurl = "http://localhost:8888/~shotakaha/kumanote/public/"
languageCode = "ja"
title = "KumaNOTE"
theme = "startbootstrap-clean-blog"
ignoreFiles = [".#"]

[permalinks]
  #post = "/blog/:year/:month/:day/"
  #post = "/blog/:filename"

[author]
  name = "Shota Takahashi"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "A Note of Kuma, for Kuma, by Kuma"
  Author = "Shota Takahashi"
  email = "shotakaha@gmail.com"
  
[[params.social]]
  title = "twitter"
  url = "https://twitter.com/shotakaha"
[[params.social]]
  title = "github"
  url = "https://github.com/shotakaha"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/shotakaha"
                                      
[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
