baseurl = "http://kuma.kek.jp/~shotakaha/kumanote/"
title = "KumaNOTE"
canonifyurls = true
theme = "hugo-future-imperfect"
languageCode = "ja"
ignoreFiles = [".#"]

[permalinks]
  #post = "/blog/:year/:month/:day/"
  #post = "/blog/:filename"

[author]
  name = "Shota Takahashi"

[params]
DateForm = "Mon, Jan 2, 2006"
Description = "A Note of Kuma, for Kuma, by Kuma"
Author = "Shota Takahashi"
email = "shotakaha+kumanote@gmail.com"

# Sets the meta tag description, usually reserved for the main page
description = "A note of Kuma, for Kuma, by Kuma"
# This will appear on the top left of the navigation bar
navbarTitle          = "Future Imperfect"
# Social media buttons that appear on the sidebar
socialAppearAtTop    = true
socialAppearAtBottom = true
# set this to the section name if section is not post
viewMorePostLink     = "post/"

# Optional Params
    categoriesByCount    = true
    includeReadingTime   = true
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # Please see the favicon partial template for more information
    loadFavicon          = false
    faviconVersion       = ""

    # Load custom CSS or JavaScript files. This replaces the deprecated params
    # minifiedFilesCSS and minifiedFilesJS. The variable is an array so that you
    # can load multiple files if necessary. You can also load the standard theme
    # files by adding the value, "default".
    # customCSS            = ["default", "/path/to/file"]
    # customJS             = ["default", "/path/to/file"]

    # Loading min files for exampleSite
    # customCSS            = ["/css/main.min.css"]
    # customJS             = ["/js/main.min.js"]

# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[params.intro]
    header    = "KumaNOTE"
    paragraph = "A Note of Kuma, for Kuma, by Kuma"
    about     = "Hi, my name is Kuma"

# This will also appear on the sidebar.
# A width of less than 100px is recommended
# This is optional
[params.intro.pic]
    src       = "/logo/bear.png"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = false
    imperfect = true
    width     = ""
    alt       = "KumaNOTE"

# Adjust the amount of recent posts on the sidebar.
# This is optional. The default value 5 will be used
[params.postAmount]
    sidebar = 2

# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar
[social]
github          = "shotakaha"
bitbucket       = "shotakaha"
jsfiddle        = ""
codepen         = ""
foursquare      = ""
dribbble        = ""
deviantart      = ""
behance         = ""
flickr          = ""
instagram       = ""
youtube         = "shotakaha"
vimeo           = ""
vine            = ""
medium          = ""
wordpress       = ""
tumblr          = ""
xing            = ""
linkedin        = ""
slideshare      = ""
stackoverflow   = ""
reddit          = ""
pinterest       = ""
googleplus      = ""
facebook        = "shotakaha"
facebook_admin  = ""
twitter_domain  = ""
twitter         = "shotakaha"
email           = ""


[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
[[menu.main]]
  name = "HTML"
  url = "/docs/html/"
  weight = -170
[[menu.main]]
  name = "PDF"
  url = "/docs/latex/KumaNote.pdf"
  weight = -170
